### ISSUE TITLE
Clean up `fastly-api-client` repo

### ISSUE THREAD

**Issue by ioannakok** [guardian/fastly-api-client#36]
I gathered in one ticket:
* some existing open issues
* https://github.com/guardian/fastly-api-client/pull/35
* And this tasklist: https://github.com/guardian/fastly-api-client/pull/35#issuecomment-2057024617

```[tasklist]
### Tasks
- [ ] https://github.com/guardian/fastly-api-client/issues/32
- [ ] https://github.com/guardian/fastly-api-client/issues/33
- [ ] https://github.com/guardian/fastly-api-client/pull/35
- [ ] https://github.com/guardian/fastly-api-client/pull/34
- [ ] https://github.com/guardian/fastly-api-client/issues/39
- [ ] https://github.com/guardian/fastly-api-client/issues/40
- [ ] https://github.com/guardian/fastly-api-client/issues/41
```

**Comment by ioannakok** [comment]
🎉
